
@startuml
interface IModuleInterface

interface IKLVImgMediaModule
interface IKLVImgMediaModule extends IModuleInterface

IKLVImgMediaModule : FKLVImgMediaGlobalCache GlobalCache 
IKLVImgMediaModule : GetGlobalCache()
IKLVImgMediaModule : CreatePlayer()


class FKLVImgMediaModule extends IKLVImgMediaModule
FKLVImgMediaModule --> FKLVImgMediaScheduler : creates 
FKLVImgMediaModule --> FKLVImgMediaGlobalCache : creates 
FKLVImgMediaModule --> FKLVImgMediaPlayer: creates 

@enduml
