
@startuml

interface IKLVImgMediaReader
interface IMediaClockSink
interface IKLVImgMediaScheduler

class FKLVImgMediaLoader
class FKLVGenericImgMediaReader extends IKLVImgMediaReader
FKLVImgMediaLoader --> FKLVGenericImgMediaReader : owns 

class FKLVImgMediaScheduler extends IMediaClockSink 
class FKLVImgMediaScheduler extends IKLVImgMediaScheduler 
FKLVImgMediaLoader --> FKLVImgMediaScheduler : owns 

IKLVImgMediaScheduler : GetWorkOrReturnToPool()

@enduml
