
@startuml
interface IMediaPlayerFactory
interface IModuleInterface
class FKLVImgMediaFactoryModule extends IMediaPlayerFactory
class FKLVImgMediaFactoryModule extends IModuleInterface
FKLVImgMediaFactoryModule : CanPlayUrl()
FKLVImgMediaFactoryModule : Object[] SupportedUriSchemes
FKLVImgMediaFactoryModule --> UKLVImgMediaSettings

@enduml
