
@startuml
UObject <|-- UKLVImgMediaSettings
FKLVImgMediaFactoryModule --> UKLVImgMediaSettings : creates 
FKLVImgMediaGlobalCache --> UKLVImgMediaSettings : uses 
FKLVImgMediaScheduler --> UKLVImgMediaSettings : uses 

@enduml
