@startuml GameplayAbilityDiagram
class GameplayAbility
class AbilitySystemComponent
class LyraPlayerState
class LyraAbilitySystemComponent
class LyraGameplayAbilitySet <<data>>
class LyraGameplayAbility
class LyraCharacter


GameplayAbility <|-- LyraGameplayAbility
AbilitySystemComponent <|-- LyraAbilitySystemComponent
LyraAbilitySystemComponent o-- LyraGameplayAbility: when granted 
LyraGameplayAbilitySet --> "*" LyraGameplayAbility: refers to
ActorComponent <|-- PawnComponent
ActorComponent <|-- AbilitySystem
PawnComponent <|-- LyraPawnComponent
Pawn <-- LyraCharacter
LyraCharacter o--> LyraPawnExtensionComponent
LyraPawnComponent <|-- LyraPawnExtensionComponent
LyraPawnExtensionComponent o--> LyraAbilitySystemComponent
PlayerController o--> LyraPlayerState : owns 
@enduml