@startuml
UObject <|-- UGameFeatureAction
UGameFeatureAction <|-- UGameFeatureAction_WorldActionBase
UGameFeatureAction_WorldActionBase <|-- UGameFeatureAction_AddAbilities
UGameFeatureAction_WorldActionBase <|-- UGameFeatureAction_AddInputContextMapping
UGameFeatureAction_WorldActionBase <|-- UGameFeatureAction_AddLevelInstances
UGameFeatureAction_WorldActionBase <|-- UGameFeatureAction_AddWorldSystem
UGameFeatureAction_WorldActionBase <|-- UGameFeatureAction_AddSpawnedActors

UGameFeatureAction_AddAbilities --> FGameFeatureAbilitiesEntry
FGameFeatureAbilitiesEntry --> FAncientGameAttributesMapping
@enduml
