
@startuml
interface IMediaPlayer
interface IMediaCache
interface IMediaControls
interface IMediaView
interface IMediaTracks
interface IMediaSamples

interface IModuleInterface

interface IMediaTextureSample

class FScreenCapPlayer implements IMediaPlayer
class FScreenCapPlayer implements IMediaCache
class FScreenCapPlayer implements IMediaControls
class FScreenCapPlayer implements IMediaView
class FScreenCapPlayer implements IMediaTracks
class FScreenCapPlayer implements IMediaSamples

class FScreenCapPlayerModule implements IModuleInterface

class ScreenCapMediaTextureSample implements IMediaTextureSample

@enduml
